[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Spec Chum egui frontend"
default-run = "spec_chum"

[[bin]]
name = "spec_chum"
path = "src/main.rs"

[dependencies]
machine = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }

[lints]
workspace = true

