[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Spec Chum egui frontend"
default-run = "spec_chum"

[lib]
name = "app"
path = "src/lib.rs"

[[bin]]
name = "spec_chum"
path = "src/main.rs"

[dependencies]
machine = { workspace = true }
formats = { workspace = true }
tape = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
cpal = { workspace = true }
rfd = "0.15"
anyhow = { workspace = true }

[lints]
workspace = true
